server:
  port: 9527

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/hr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: root

#  rabbitmq:
#    port: 5672
#    host: 192.168.200.128
#    username: boluo
#    password: 123456

