server:
  port: 9527

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3307/hr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: root

  rabbitmq:
    port: 5672
    host: 127.0.0.1
    username: root
    password: 123456

  main:
    banner-mode: off
# 分页配置参数
page helper:
  page-size-zero: true
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql