server:
  port: 9528

spring:
  mail:
    host: smtp.qq.com
    protocol: smtp
    default-encoding: UTF-8
    username: 1352955539@qq.com
    password: lenilwqjnvaqfieh
    port: 587

    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory

  rabbitmq:
    port: 5672
    host: 127.0.0.1
    username: root
    password: 123456
    listener:
      direct:
        acknowledge-mode: auto
      simple:
        prefetch: 1
        retry:
          enabled: true
  main:
    banner-mode: off

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:10101/hr?useTimezone=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    name: hr
