import Vue from 'vue'
import {
  Avatar,
  Button,
  Form,
  FormItem,
  Input,
  Card,
  Message,
  Dialog,
  Container,
  Header,
  Aside,
  Menu,
  Submenu,
  MenuItem,
  MenuItemGroup,
  Main,
  Breadcrumb,
  BreadcrumbItem,
  Tabs,
  TabPane,
  Table,
  TableColumn,
  MessageBox,
  Option,
  Select,
  Tag,
  Collapse,
  CollapseItem,
  Tree,
  Switch,
  Pagination,
  Row,
  Col,
  Radio,
  DatePicker,
  Loading,
  Upload,
  Notification,
  Tooltip,
  Dropdown,
  DropdownMenu,
  DropdownItem,
  Badge,
  Link,
  Popover,
  Popconfirm,
  Drawer,
  Autocomplete,
  Empty,
  Descriptions,
  DescriptionsItem
} from 'element-ui'

Vue.use(DescriptionsItem)
Vue.use(Autocomplete)
Vue.use(Drawer)
Vue.use(Popconfirm)
Vue.use(Popover)
Vue.use(Link)
Vue.use(Badge)
Vue.use(Avatar)
Vue.use(Dropdown)
Vue.use(DropdownMenu)
Vue.use(DropdownItem)
Vue.use(Tooltip)
Vue.use(Button)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Card)
Vue.use(Dialog)
Vue.use(Container)
Vue.use(Header)
Vue.use(Aside)
Vue.use(Menu)
Vue.use(Submenu)
Vue.use(MenuItem)
Vue.use(MenuItemGroup)
Vue.use(Main)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Tabs)
Vue.use(TabPane)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Option)
Vue.use(Select)
Vue.use(Tag)
Vue.use(Collapse)
Vue.use(CollapseItem)
Vue.use(Tree)
Vue.use(Switch)
Vue.use(Pagination)
Vue.use(Row)
Vue.use(Col)
Vue.use(Radio)
Vue.use(DatePicker)
Vue.use(Loading)
Vue.use(Upload)
Vue.use(Empty)
Vue.use(Descriptions)
Vue.prototype.$message = Message
Vue.prototype.$confirm = MessageBox.confirm
Vue.prototype.$notify = Notification
